name: build push on github package
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build_push_github_packages:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
         images: |
            ghcr.io/nourchawebi/devops-avril/astonvilla
         tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name : set up qemu
        uses: docker/setup-qemu-action@v2
      - name : set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name : login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GHCR_TOKEN}}
      - name: build and push docker image
        uses: docker/build-push-action@v4
        with:
          context : .
          push : true
          tags: ${{steps.meta.outputs.tags}}


